pos1-posmode=8
pos1-navsys=5
pos1-frequency=2
pos1-soltype=2
pos1-elmask=10
pos1-iono=3
pos1-tropo=3
pos1-sateph=1
pos1-posopt1=1
pos1-posopt2=1
pos1-posopt3=1
pos1-posopt4=0
out-solformat=0
out-outhead=1
out-outopt=1
out-timesys=0
stats-errratio=100
stats-errphase=0.003
stats-errphaseel=0.003
stats-reject=30.0
ant1-postype=xyz
ant1-pos1=4010100.5014
ant1-pos2=-4259928.2130
ant1-pos3=-2533539.1616
file-antex=/home/bernardo-a-lima/Documents/projetoIC/GNSS/igs20.atx