pos1-posmode=ppp-static
pos1-frequency=l1+l2
pos1-soltype=combined
pos1-elmask=10
pos1-iono=iono-free
pos1-tropo=saasth
pos1-sateph=precise
file-antex=
out-solformat=llh
out-outhead=on
out-outopt=on
out-timesys=gpst
stats-errratio=100
stats-errphase=0.003
stats-errphaseel=0.003